[project]
name = "myOfflineAi"
version = "1.0"
description = "A Flask UI for Ollama"
requires-python = "==3.10.*"
dependencies = [
	"flask==3.1.2",
	"ollama==0.6.0",
	"pymupdf==1.26.4",
	"pillow==11.3.0",
	"requests==2.32.5",
]
